import { ar } from 'vuetify/lib/locale'

export default {
  ...ar,
  TRANSLATION: 'ترجمة',
  // Admin: 'المسؤول',
  // 'General Settings': 'الإعدادات العامة',
  // 'Admin Privacy Policy': 'سياسة الخصوصية',
  // 'Admin Service Provider': 'مقدم خدمة المسؤول',
  // 'Admin Terms and Conditions': 'الشروط والأحكام',
  // Dashboard: 'الاحصائيات',
  // Apartments: 'الشقق',
  // 'E-Contracts': 'العقود الالكترونية',
  // 'Payment Requests': 'طلبات الدفع',
  // Clients: 'العملاء',
  // Users: 'المستخدمون',
  // Notifications: 'الاشعارات',
  // Announcement: 'الاعلانات',
  // 'Privacy Policy': 'سياسة الخصوصية',
  // 'Contact us': 'تواصل معنا',
  // 'Terms and Conditions': 'الشروط والأحكام',
  // Logout: 'تسجيل الخروج',
  // 'Admin Dashboard': 'لوحة تحكم المسؤول',
  // 'Admin Apartments': 'شقق إدارية',
  // 'Admin E-Contracts': 'العقود الإلكترونية الإدارية',
  // 'Admin Clients': 'العملاء الإداريين',
  // 'Admin Staffs': 'طاقم الإدارة',
  // 'Admin Staff': 'طاقم الإدارة',
  // 'Admin Service Provider': 'مقدم خدمة المسؤول',
  // 'Admin Bank Employee': 'موظف بنك إداري',
  // 'New Bank Employee': 'موظف بنك جديد',
  // 'Bankers': 'مصرفيون',
  // 'Admin Previewer': 'عارض المسؤول',
  // 'New Previewer': 'عارض جديد',
  // 'Service Provider': 'مقدم الخدمة',
  // 'Bank Employee': 'الموظف الإداري',
  // 'Previewer': 'عارض',
  // 'Per month statistics': 'إحصائيات شهرية',
  // 'Properties Added': 'تمت إضافة الخصائص',
  // 'Rented Apartments': 'شقق مستأجرة',
  // 'Registered Users': 'المستخدمون المسجلون',
  // key1: "لوحة القيادة",
  // key2: "key 2 internationalization",
  // namespace: {
  //   key3: "key 3 internationalization"
  // },
  // table_header: {
  //   EMAIL: "البريد الإلكتروني",
  //   NAME: "اسم",
  //   'CONTACT NUMBER': "رقم الاتصال",
  //   CITY: "مدينة",
  //   CATEGORY: "الفئة",
  //   RENTED: "مستأجرة",
  //   ACTION: "عمل",
  //   PRICE: "سعر",
  //   STATUS: "حالة",
  //   TYPE: "يكتب",
  //   IMAGE: "صورة",
  //   OWNER: "صاحبة",
  //   "PROPERTY NAME": "اسم الخاصية",
  //   DOB: "تاريخ الولادة",
  //   "NATIONAL ID": "الهوية الوطنية",
  //   ID: "بطاقة تعريف",
  //   'MOBILE NUMBER': 'رقم الهاتف المحمول',
  //   'ASSIGN TO': 'يسند إلى',
  // },
  // tabs: {
  //   'Assigned to me': 'تعيين لي',
  //   'Requests': 'الطلبات',
  // },
  // 'Latest Clients': 'أحدث العملاء',
  // 'Latest Products': 'أحدث المنتجات',
  // 'Assign to me': 'خصص لي',
  // View : 'رأي',
  // Published: 'نشرت',
  // 'Assigned to me': 'تعيين لي',
  // Requests: 'الطلبات',
  // 'Admin Staff': 'طاقم إداري جديد',
  // 'New Admin Staff': 'طاقم إداري جديد',
  // 'Providers': 'الموفرون',
  // 'New Provider': 'مزود جديد',
  // 'entries per page': 'إدخالات في كل صفحة',
  // Accept: 'قبول',
  // Accepted: 'وافقت',
  // Reject: 'رفض',
  // Rejected: 'مرفوض',
  // Edit: 'يحرر',
  // Delete: 'حذف',
  // 'Sign In': 'تسجيل الدخول',
  // 'Enter your phone number and password to Sign In': 'أدخل رقم هاتفك وكلمة المرور لتسجيل الدخول',
  // 'Email or Phone Number': 'البريد الإلكتروني أو رقم الهاتف',
  // 'Password': 'كلمة المرور',
  // name: 'اسم',
  // email: 'البريد الإلكتروني',
  // contact_number: 'رقم الاتصال',
  // password: 'كلمه السر',
  // password_confirmation: 'تأكيد كلمة المرور',
  // 'Add Previewer': 'إضافة عارض',
  // 'Continue to ejar contract': 'استمر في عقد إيجار',
  // 'Approve the owner/proxy request to upload apartment': 'الموافقة على طلب المالك / التوكيل لتحميل الشقة',

  Admin: 'المسؤول',
  'General Settings': 'الإعدادات العامة',
  'Admin Privacy Policy': 'سياسة الخصوصية ',
  'Admin Terms and Conditions': 'الشروط والأحكام ',
  Dashboard: 'الاحصائيات',
  Apartments: 'الشقق',
  'E-Contracts': 'العقود الالكترونية',
  'Payment Requests': 'طلبات الدفع',
  Clients: 'العملاء',
  Users: 'المستخدمون',
  Notifications: 'الاشعارات',
  Provider: 'مزود',
  Services: 'خدمات',
  services: 'خدمات',
  Announcement: 'الاعلانات',
  'Privacy Policy': 'سياسة الخصوصية',
  'Contact us': 'تواصل معنا',
  'Terms and Conditions': 'الشروط والأحكام',
  Logout: 'تسجيل الخروج',
  'Admin Dashboard': 'احصائيات المسؤول',
  'Admin Apartments': 'الشقق',
  'Admin E-Contracts': 'العقود الاكترونية',
  'Admin Clients': 'العملاء',
  'Admin Staffs': 'طاقم الادارة',
  'Admin Service Provider': 'مقدم الخدمة',
  'Admin Bank Employee': 'موظف البنك',
  'Admin Previewer': 'المعاين',
  'New Previewer': 'معاين جديد',
  'Service Provider': 'مقدم خدمة',
  'Bank Employee': 'موظف البنك',
  'New Bank Employee': 'موظف بنك جديد',
  'Bankers': 'موظف البنك',
  'Previewer': 'المعاين',
  'Per month statistics': 'احصائيات شهرية',
  'Properties Added': 'العقارات المضافة',
  'Rented Apartments': 'الشقق المؤجرة',
  'Registered Users': 'المستخدمون ',
  key1: "key 1 internationalization",
  key2: "key 2 internationalization",


  table_header: {
    EMAIL: "البريد الإلكتروني",
    NAME: "الاسم",
    'CONTACT NUMBER': "رقم التواصل",
    CITY: "المدينة",
    CATEGORY: "الفئة",
    RENTED: "مستأجرة",
    ACTION: "إجراء",
    PRICE: "السعر",
    STATUS: "الحلة",
    TYPE: "النوع",
    IMAGE: "الصور",
    OWNER: "المالك",
    "PROPERTY NAME": "اسم العقار",
    DOB: "تاريخ الميلاد",
    "NATIONAL ID": "الهوية ",
    ID: "المعرّف",
    'MOBILE NUMBER': 'رقم الجوال',
    'ASSIGN TO': 'اسناد إلى',
    'CUSTOMER NAME': "اسم الزبون",
    DATE: "تاريخ",
    TIME: "الوقت",
  },
  tabs: {
    'Assigned to me': 'اسناده لي',
    'Requests': 'الطلبات',
  },
  'Latest Clients': 'أحدث العملاء',
  'Latest Products': 'أحدث المنتجات',
  'Assign to me': 'اسناده لي',
  View : 'عرض',
  Published: 'تم نشرها',
  'Assigned to me': 'أسندت لي',
  Requests: 'الطلبات',
  'Admin Staff': 'طاقم إداري ',
  'New Admin Staff': 'طاقم إداري جديد',
  'Providers': 'مقدمي الخدمات',
  'New Provider': 'مقدم خدمة جديد',
  'entries per page': 'صفوف في كل صفحة',
  Accept: 'قبول',
  Accepted: 'تمت الموافقة',
  Reject: 'رفض',
  Rejected: 'تم الرفض',
  Edit: 'تعديل',
  Delete: 'حذف',
  'Sign In': 'تسجيل الدخول',
  'Enter your phone number and password to Sign In': 'أدخل رقم هاتفك وكلمة المرور لتسجيل الدخول',
  'Email or Phone Number': 'البريد الإلكتروني أو رقم الهاتف',
  'Password': 'كلمة المرور',
  name: 'الاسم',
  email: 'البريد الإلكتروني',
  contact_number: 'رقم التواصل',
  password: 'كلمه السر',
  password_confirmation: 'تأكيد كلمة المرور',
  'Add Previewer': 'إضافة معاين',
  'Continue to ejar contract': 'استمر في عقد إيجار',
  'Approve the owner/proxy request to upload apartment': 'الموافقة على عرض الشقة في التطبيق',
  'Change Status': 'تغيير الوضع',
  'Send Offer': 'إرسال العرض',
}

