// import { en } from 'vuetify/lib/locale'

// export default {
//   ...en,
//   TRANSLATION: 'TRANSLATION',
//   Admin: 'Admin',
//   Provider: 'Provider',
//   Services: 'Services',
//   Products: 'Products',
//   Orders: 'Orders',
//   Dashboard: 'Dashboard',
//   Apartments: 'Apartments',
//   'E-Contracts': 'E-Contracts',
//   'Payment Requests': 'Payment Requests',
//   Clients: 'Clients',
//   Users: 'Users',
//   Notifications: 'Notifications',
//   Announcement: 'Announcement',
//   Logout: 'Logout',
//   'Admin Dashboard': 'Admin Dashboard',
//   'Per month statistics': 'Per month statistics',
//   'Properties Added': 'Properties Added',
//   'Rented Apartments': 'Rented Apartments',
//   'Registered Users': 'Registered Users',
//   key1: "key 1 internationalization",
//   key2: "key 2 internationalization",

//   table_header: {
//     EMAIL: "EMAIL",
//     NAME: "NAME",
//     'CONTACT NUMBER': "CONTACT NUMBER",
//     CITY: "CITY",
//     RENTED: "RENTED",
//     ACTION: "ACTION",
//     PRICE: "PRICE",
//     STATUS: "STATUS",
//     'CUSTOMER NAME': "CUSTOMER NAME",
//     TYPE: "TYPE",
//     DATE: "DATE",
//     TIME: "TIME",
//     COLORS: "COLORS",
//     QUANTITY: "QUANTITY",
//     "DATE ADDED": "DATE ADDED",
//     "PRODUCT NAME": "PRODUCT NAME",
//   },
//   tabs: {
//     'Assigned to me': 'Assigned to me',
//     'Requests': 'Requests',
//   }
// }
import { en } from 'vuetify/lib/locale'

export default {
  ...en,
  TRANSLATION: 'TRANSLATION',
  Admin: 'Admin',
  Provider: 'Provider',
  'General Settings': 'General Settings',
  'Admin Privacy Policy': 'Admin Privacy Policy',
  'Admin Terms and Conditions': 'Admin Terms and Conditions',
  Dashboard: 'Dashboard',
  Apartments: 'Apartments',
  Services: 'Services',
  'E-Contracts': 'E-Contracts',
  'Payment Requests': 'Payment Requests',
  Clients: 'Clients',
  Users: 'Users',
  Notifications: 'Notifications',
  Announcement: 'Announcement',
  'Privacy Policy': 'Privacy Policy',
  'Contact us': 'Contact us',
  'Terms and Conditions': 'Terms and Conditions',
  Logout: 'Logout',
  'Admin Dashboard': 'Admin Dashboard',
  'Admin Apartments': 'Admin Apartments',
  'Admin E-Contracts': 'Admin E-Contracts',
  'Admin Clients': 'Admin Clients',
  'Admin Staffs': 'Admin Staffs',
  'Admin Service Provider': 'Admin Service Provider',
  'Admin Bank Employee': 'Admin Bank Employee',
  'Admin Previewer': 'Admin Previewer',
  'New Previewer': 'New Previewer',
  'Service Provider': 'Service Provider',
  'Bank Employee': 'Admin Employee',
  'New Bank Employee': 'New Bank Employee',
  'Bankers': 'New Bank Employee',
  'Previewer': 'Bankers',
  'Per month statistics': 'Per month statistics',
  'Properties Added': 'Properties Added',
  'Rented Apartments': 'Rented Apartments',
  'Registered Users': 'Registered Users',
  key1: "key 1 internationalization",
  key2: "key 2 internationalization",

  table_header: {
    EMAIL: "EMAIL",
    NAME: "NAME",
    'CONTACT NUMBER': "CONTACT NUMBER",
    CITY: "CITY",
    CATEGORY: "CATEGORY",
    RENTED: "RENTED",
    ACTION: "ACTION",
    PRICE: "PRICE",
    STATUS: "STATUS",
    TYPE: "TYPE",
    IMAGE: "IMAGE",
    OWNER: "OWNER",
    "PROPERTY NAME": "PROPERTY NAME",
    DOB: "DOB",
    "NATIONAL ID": "NATIONAL ID",
    ID: "ID",
    'MOBILE NUMBER': 'MOBILE NUMBER',
    'ASSIGN TO': 'ASSIGN TO',
    'CUSTOMER NAME': "CUSTOMER NAME",
    DATE: "DATE",
    TIME: "TIME",
  },
  tabs: {
    'Assigned to me': 'Assigned to me',
    'Requests': 'Requests',
  },
  'Latest Clients': 'Latest Clients',
  'Latest Products': 'Latest Products',
  'Assign to me': 'Assign to me',
  'View': 'View',
  'Published': 'Published',
  'Assigned to me': 'Assigned to me',
  'Requests': 'Requests',
  'Admin Staff': 'Admin Staffs',
  'New Admin Staff': 'New Admin Staff',
  'Providers': 'Providers',
  'New Provider': 'New Provider',
  'entries per page': 'entries per page',
  Accept: 'Accept',
  Accepted: 'Accepted',
  Reject: 'Reject',
  Rejected: 'Rejected',
  Edit: 'Edit',
  Delete: 'Delete',
  'Sign In': 'Sign In',
  'Enter your phone number and password to Sign In': 'Enter your phone number and password to Sign In',
  'Email or Phone Number': 'Email or Phone Number',
  'Password': 'Password',
  name: 'name',
  email: 'email',
  contact_number: 'contact_number',
  password: 'password',
  password_confirmation: 'password_confirmation',
  'Add Previewer': 'Add Previewer',
  'Continue to ejar contract': 'Continue to ejar contract',
  'Approve the owner/proxy request to upload apartment': 'Approve the owner/proxy request to upload apartment',
  'Change Status': 'Change Status',
  'Send Offer': 'Send Offer',
}